"num_shots","prompt","expected_json_str","generated_json_str","valid_json","schema_match","key_f1","key_precision","key_recall","item_f1","item_precision","item_recall","tree_edit_similarity","tree_edit_distance","generation_time"
"0","Model an ABS cylinder 20mm radius and 102mm height. Pin the base and apply 165N at coordinates (20, ","{""geometry"": {""type"": ""cylinder"", ""dimensions"": {""outer_radius"": 20, ""inner_radius"": 0, ""height"": 102}, ""origin"": {""x"": 0, ""y"": 0, ""z"": 0}, ""orientation"": {""primary_axis"": ""z""}}, ""material"": {""type"": ""ABS""}, ""boundary_conditions"": [{""type"": ""pinned"", ""location"": {""method"": ""descriptor"", ""value"": ""bottom_face""}}], ""loads"": [{""type"": ""force"", ""magnitude"": 165, ""direction"": [0, 0, -1], ""location"": {""method"": ""coordinates"", ""point"": [20, 20, 102]}}]}","INVALID","False","False","0.0","0.0","0.0","0.0","0.0","0.0","0.0","inf","7.867949962615967"
"0","Generate a box geometry using polycarbonate with 83mm x 46mm x 68mm. Apply pin the bottom right corn","{""geometry"": {""type"": ""box"", ""dimensions"": {""length"": 83, ""width"": 46, ""height"": 68}, ""origin"": {""x"": 0, ""y"": 0, ""z"": 0}, ""orientation"": {""primary_axis"": ""z""}}, ""material"": {""type"": ""POLYCARBONATE""}, ""boundary_conditions"": [{""type"": ""pinned"", ""location"": {""method"": ""descriptor"", ""value"": ""bottom_right_corner""}}], ""loads"": [{""type"": ""pressure"", ""magnitude"": 10000000, ""location"": {""method"": ""descriptor"", ""value"": ""bottom_face""}}]}","{""geometry"": {""type"": ""box"", ""dimensions"": {""length"": 83, ""width"": 46, ""height"": 68}}, ""material"": {""type"": ""polycarbonate"", ""properties"": {""elastic_modulus"": 2100000000.0, ""poissons_ratio"": 0.3, ""density"": 1250.0}}, ""boundary_conditions"": [{""type"": ""pin"", ""location"": {""description"": ""bottom right corner""}}], ""loads"": [{""type"": ""pressure"", ""magnitude"": 10000000.0, ""direction"": {""x"": 0, ""y"": 0, ""z"": -1}, ""location"": {""description"": ""bottom face""}}]}","True","False","0.5","0.5","0.5","0.3125","0.3125","0.3125","0.6590909090909092","30.0","15.599270820617676"
"0","Generate FEA model: sphere, material polypropylene, radius 38mm. BC: Constrain the front face. Load:","{""geometry"": {""type"": ""sphere"", ""dimensions"": {""outer_radius"": 38, ""inner_radius"": 0}, ""origin"": {""x"": 0, ""y"": 0, ""z"": 0}, ""orientation"": {""primary_axis"": ""z""}}, ""material"": {""type"": ""POLYPROPYLENE""}, ""boundary_conditions"": [{""type"": ""fixed"", ""location"": {""method"": ""descriptor"", ""value"": ""front_face""}}], ""loads"": [{""type"": ""pressure"", ""magnitude"": 4000000, ""location"": {""method"": ""descriptor"", ""value"": ""inner_surface""}}]}","{""geometry"": {""type"": ""sphere"", ""dimensions"": {""radius"": 38}}, ""material"": {""type"": ""polypropylene"", ""properties"": {""elastic_modulus"": null, ""poissons_ratio"": null, ""density"": null}}, ""boundary_conditions"": [{""type"": ""constrained"", ""location"": {""description"": ""front face""}}], ""loads"": [{""type"": ""distributed_load"", ""magnitude"": 4000000, ""direction"": {""x"": 0, ""y"": 0, ""z"": -1}, ""location"": {""description"": ""inner surface""}}]}","True","False","0.3448275862068966","0.35714285714285715","0.3333333333333333","0.13793103448275862","0.14285714285714285","0.13333333333333333","0.5853658536585367","34.0","9.274744987487793"
"0","Make a nylon pa6 sphere part with 40mm in radius. Apply roller bc at the bottom left corner and 180n","{""geometry"": {""type"": ""sphere"", ""dimensions"": {""outer_radius"": 40, ""inner_radius"": 0}, ""origin"": {""x"": 0, ""y"": 0, ""z"": 0}, ""orientation"": {""primary_axis"": ""z""}}, ""material"": {""type"": ""NYLON_PA6""}, ""boundary_conditions"": [{""type"": ""roller"", ""location"": {""method"": ""descriptor"", ""value"": ""bottom_left_corner""}}], ""loads"": [{""type"": ""force"", ""magnitude"": 180, ""direction"": [0.707, 0, -0.707], ""location"": {""method"": ""descriptor"", ""value"": ""back_left_corner""}}]}","{""geometry"": {""type"": ""sphere"", ""dimensions"": {""radius"": 40}}, ""material"": {""type"": ""nylon"", ""properties"": {""elastic_modulus"": 0, ""poissons_ratio"": 0, ""density"": 0}}, ""boundary_conditions"": [{""type"": ""roller"", ""location"": {""description"": ""bottom left corner""}}], ""loads"": [{""type"": ""force"", ""magnitude"": 180, ""direction"": {""x"": 0, ""y"": 0, ""z"": -1}, ""location"": {""description"": ""back left corner""}}]}","True","False","0.3125","0.35714285714285715","0.2777777777777778","0.25","0.2857142857142857","0.2222222222222222","0.6259213483146068","33.293","13.762425899505615"
"0","Generate FEA model: cylinder, material bronze, 22mm radius, 180mm height. BC: Pin the top left corne","{""geometry"": {""type"": ""cylinder"", ""dimensions"": {""outer_radius"": 22, ""height"": 180, ""inner_radius"": 0}, ""origin"": {""x"": 0, ""y"": 0, ""z"": 0}, ""orientation"": {""primary_axis"": ""z""}}, ""material"": {""type"": ""BRONZE""}, ""boundary_conditions"": [{""type"": ""pinned"", ""location"": {""method"": ""descriptor"", ""value"": ""top_left_corner""}}], ""loads"": [{""type"": ""force"", ""magnitude"": 95, ""direction"": [0, 0, -1], ""location"": {""method"": ""descriptor"", ""value"": ""center_point""}}]}","INVALID","False","False","0.0","0.0","0.0","0.0","0.0","0.0","0.0","inf","11.132944583892822"
