"num_shots","prompt","expected_json_str","generated_json_str","valid_json","schema_match","key_f1","key_precision","key_recall","item_f1","item_precision","item_recall","tree_edit_similarity","tree_edit_distance","generation_time"
"10","Create a glass borosilicate cone with 35mm base radius, pointed tip, and 32mm height. Apply symmetry","{""geometry"": {""type"": ""cone"", ""dimensions"": {""bottom_radius"": 35, ""top_radius"": 0, ""height"": 32}, ""origin"": {""x"": 0, ""y"": 0, ""z"": 0}, ""orientation"": {""primary_axis"": ""z""}}, ""material"": {""type"": ""GLASS_BOROSILICATE""}, ""boundary_conditions"": [{""type"": ""symmetry"", ""location"": {""method"": ""descriptor"", ""value"": ""bottom_center_point""}}], ""loads"": [{""type"": ""force"", ""magnitude"": 80, ""direction"": [0, 1, 0], ""location"": {""method"": ""descriptor"", ""value"": ""top_face""}}]}","INVALID","False","False","0.0","0.0","0.0","0.0","0.0","0.0","0.0","inf","27.466766595840454"
"10","Create a rubber silicone cylinder with 10mm radius, 105mm height. Symmetry constraint at the center ","{""geometry"": {""type"": ""cylinder"", ""dimensions"": {""outer_radius"": 10, ""height"": 105, ""inner_radius"": 0}, ""origin"": {""x"": 0, ""y"": 0, ""z"": 0}, ""orientation"": {""primary_axis"": ""z""}}, ""material"": {""type"": ""RUBBER_SILICONE""}, ""boundary_conditions"": [{""type"": ""symmetry"", ""location"": {""method"": ""descriptor"", ""value"": ""center_point""}}], ""loads"": [{""type"": ""force"", ""magnitude"": 180, ""direction"": [0, 0, 1], ""location"": {""method"": ""descriptor"", ""value"": ""back_face""}}]}","INVALID","False","False","0.0","0.0","0.0","0.0","0.0","0.0","0.0","inf","54.33632850646973"
"10","Generate a box geometry using aluminum 2024 with 54mm x 42mm x 29mm. Apply fix the left face and app","{""geometry"": {""type"": ""box"", ""dimensions"": {""length"": 54, ""width"": 42, ""height"": 29}, ""origin"": {""x"": 0, ""y"": 0, ""z"": 0}, ""orientation"": {""primary_axis"": ""z""}}, ""material"": {""type"": ""ALUMINUM_2024""}, ""boundary_conditions"": [{""type"": ""fixed"", ""location"": {""method"": ""descriptor"", ""value"": ""left_face""}}], ""loads"": [{""type"": ""pressure"", ""magnitude"": 4000000, ""location"": {""method"": ""descriptor"", ""value"": ""top_face""}}]}","INVALID","False","False","0.0","0.0","0.0","0.0","0.0","0.0","0.0","inf","55.96477818489075"
"10","FEA setup: box geometry, nylon pa6 material, size length 40mm, width 20mm, height 70mm. Symmetry con","{""geometry"": {""type"": ""box"", ""dimensions"": {""length"": 40, ""width"": 20, ""height"": 70}, ""origin"": {""x"": 0, ""y"": 0, ""z"": 0}, ""orientation"": {""primary_axis"": ""z""}}, ""material"": {""type"": ""NYLON_PA6""}, ""boundary_conditions"": [{""type"": ""symmetry"", ""location"": {""method"": ""descriptor"", ""value"": ""front_left_corner""}}], ""loads"": [{""type"": ""force"", ""magnitude"": 800, ""direction"": [0, 0, 1], ""location"": {""method"": ""descriptor"", ""value"": ""bottom_left_corner""}}]}","{""geometry"": {""type"": ""box"", ""dimensions"": {""length"": 40, ""width"": 20, ""height"": 70}, ""origin"": {""x"": 0, ""y"": 0, ""z"": 0}, ""orientation"": {""primary_axis"": ""z""}}, ""material"": {""type"": ""NYLON_PA6""}, ""boundary_conditions"": [{""type"": ""symmetry"", ""location"": {""method"": ""descriptor"", ""value"": ""front_left_corner""}}], ""loads"": [{""type"": ""force"", ""magnitude"": 800, ""direction"": [0, 0, 1], ""location"": {""method"": ""descriptor"", ""value"": ""bottom_left_corner""}}]}","True","False","1.0","1.0","1.0","1.0","1.0","1.0","1.0","0.0","7.338358163833618"
"10","Model a sphere made of pla. Dimensions: 20mm radius. Apply roller support at the left face. apply 12","{""geometry"": {""type"": ""sphere"", ""dimensions"": {""outer_radius"": 20, ""inner_radius"": 0}, ""origin"": {""x"": 0, ""y"": 0, ""z"": 0}, ""orientation"": {""primary_axis"": ""z""}}, ""material"": {""type"": ""PLA""}, ""boundary_conditions"": [{""type"": ""roller"", ""location"": {""method"": ""descriptor"", ""value"": ""left_face""}}], ""loads"": [{""type"": ""force"", ""magnitude"": 120, ""direction"": [0, -1, 0], ""location"": {""method"": ""descriptor"", ""value"": ""center_point""}}]}","{""geometry"": {""type"": ""sphere"", ""dimensions"": {""outer_radius"": 20, ""inner_radius"": 0}, ""origin"": {""x"": 0, ""y"": 0, ""z"": 0}, ""orientation"": {""primary_axis"": ""z""}}, ""material"": {""type"": ""PLA""}, ""boundary_conditions"": [{""type"": ""roller"", ""location"": {""method"": ""descriptor"", ""value"": ""left_face""}}], ""loads"": [{""type"": ""force"", ""magnitude"": 120, ""direction"": [0, 0, 1], ""location"": {""method"": ""descriptor"", ""value"": ""center_point""}}]}","True","True","1.0","1.0","1.0","0.8888888888888888","0.8888888888888888","0.8888888888888888","0.9795918367346939","2.0","6.678812742233276"
