"num_shots","prompt","expected_json_str","generated_json_str","valid_json","schema_match","key_f1","key_precision","key_recall","item_f1","item_precision","item_recall","tree_edit_similarity","tree_edit_distance","generation_time"
"1","Design a titanium gr5 box (133mm x 123mm x 72mm). Apply symmetry boundary condition at the bottom le","{""geometry"": {""type"": ""box"", ""dimensions"": {""length"": 133, ""width"": 123, ""height"": 72}, ""origin"": {""x"": 0, ""y"": 0, ""z"": 0}, ""orientation"": {""primary_axis"": ""z""}}, ""material"": {""type"": ""TITANIUM_GR5""}, ""boundary_conditions"": [{""type"": ""symmetry"", ""location"": {""method"": ""descriptor"", ""value"": ""bottom_left_corner""}}], ""loads"": [{""type"": ""pressure"", ""magnitude"": 1500000, ""location"": {""method"": ""descriptor"", ""value"": ""outer_surface""}}]}","INVALID","False","False","0.0","0.0","0.0","0.0","0.0","0.0","0.0","inf","15.17451810836792"
"1","Build a sphere from steel stainless 316 with dimensions radius 48mm. Pin the back right corner and 8","{""geometry"": {""type"": ""sphere"", ""dimensions"": {""outer_radius"": 48, ""inner_radius"": 0}, ""origin"": {""x"": 0, ""y"": 0, ""z"": 0}, ""orientation"": {""primary_axis"": ""z""}}, ""material"": {""type"": ""STEEL_STAINLESS_316""}, ""boundary_conditions"": [{""type"": ""pinned"", ""location"": {""method"": ""descriptor"", ""value"": ""back_right_corner""}}], ""loads"": [{""type"": ""pressure"", ""magnitude"": 8000000, ""location"": {""method"": ""descriptor"", ""value"": ""bottom_face""}}]}","INVALID","False","False","0.0","0.0","0.0","0.0","0.0","0.0","0.0","inf","19.4313006401062"
"1","Generate a box geometry using polycarbonate with 83mm x 46mm x 68mm. Apply pin the bottom right corn","{""geometry"": {""type"": ""box"", ""dimensions"": {""length"": 83, ""width"": 46, ""height"": 68}, ""origin"": {""x"": 0, ""y"": 0, ""z"": 0}, ""orientation"": {""primary_axis"": ""z""}}, ""material"": {""type"": ""POLYCARBONATE""}, ""boundary_conditions"": [{""type"": ""pinned"", ""location"": {""method"": ""descriptor"", ""value"": ""bottom_right_corner""}}], ""loads"": [{""type"": ""pressure"", ""magnitude"": 10000000, ""location"": {""method"": ""descriptor"", ""value"": ""bottom_face""}}]}","{""geometry"": {""type"": ""box"", ""dimensions"": {""length"": 83, ""width"": 46, ""height"": 68}, ""origin"": {""x"": 0, ""y"": 0, ""z"": 0}, ""orientation"": {""primary_axis"": ""z""}}, ""material"": {""type"": ""POLYCARBONATE""}, ""boundary_conditions"": [{""type"": ""pinned"", ""location"": {""method"": ""descriptor"", ""value"": ""bottom_right_corner""}}], ""loads"": [{""type"": ""pressure"", ""magnitude"": 10000, ""direction"": [0, 0, -1], ""location"": {""method"": ""descriptor"", ""value"": ""bottom_face""}}]}","True","True","0.9142857142857143","0.8421052631578947","1.0","0.8571428571428571","0.7894736842105263","0.9375","0.9158","7.999","7.950263261795044"
"1","Generate a box geometry using titanium gr5 with 86mm x 129mm x 37mm. Apply apply roller support at t","{""geometry"": {""type"": ""box"", ""dimensions"": {""length"": 86, ""width"": 129, ""height"": 37}, ""origin"": {""x"": 0, ""y"": 0, ""z"": 0}, ""orientation"": {""primary_axis"": ""z""}}, ""material"": {""type"": ""TITANIUM_GR5""}, ""boundary_conditions"": [{""type"": ""roller"", ""location"": {""method"": ""descriptor"", ""value"": ""bottom_right_corner""}}], ""loads"": [{""type"": ""force"", ""magnitude"": 50, ""direction"": [0, 0, 1], ""location"": {""method"": ""descriptor"", ""value"": ""top_face""}}]}","{""geometry"": {""type"": ""box"", ""dimensions"": {""length"": 129, ""width"": 86, ""height"": 37}, ""origin"": {""x"": 0, ""y"": 0, ""z"": 0}, ""orientation"": {""primary_axis"": ""z""}}, ""material"": {""type"": ""TITANIUM_GR5""}, ""boundary_conditions"": [{""type"": ""roller"", ""location"": {""method"": ""descriptor"", ""value"": ""bottom_right_corner""}}], ""loads"": [{""type"": ""force"", ""magnitude"": 50, ""direction"": {""x"": 0, ""y"": 0, ""z"": -1}, ""location"": {""method"": ""descriptor"", ""value"": ""top_face""}}]}","True","False","0.8421052631578947","0.8421052631578947","0.8421052631578947","0.7368421052631579","0.7368421052631579","0.7368421052631579","0.9542483660130718","4.666666666666667","8.773693561553955"
"1","Generate FEA model: cylinder, material brass, 42mm outer radius, 2mm wall thickness, 155mm length. B","{""geometry"": {""type"": ""cylinder"", ""dimensions"": {""outer_radius"": 42, ""height"": 155, ""inner_radius"": 40}, ""origin"": {""x"": 0, ""y"": 0, ""z"": 0}, ""orientation"": {""primary_axis"": ""z""}}, ""material"": {""type"": ""BRASS""}, ""boundary_conditions"": [{""type"": ""symmetry"", ""location"": {""method"": ""descriptor"", ""value"": ""front_left_corner""}}], ""loads"": [{""type"": ""force"", ""magnitude"": 30, ""direction"": [1, 0, 0], ""location"": {""method"": ""descriptor"", ""value"": ""back_left_corner""}}]}","{""geometry"": {""type"": ""cylinder"", ""dimensions"": {""radius"": 42, ""wall_thickness"": 2, ""length"": 155}, ""origin"": {""x"": 0, ""y"": 0, ""z"": 0}, ""orientation"": {""primary_axis"": ""z""}}, ""material"": {""type"": ""BRASS""}, ""boundary_conditions"": [{""type"": ""symmetry"", ""location"": {""method"": ""descriptor"", ""value"": ""front_left_corner""}}], ""loads"": [{""type"": ""force"", ""magnitude"": 30, ""direction"": {""x"": 1, ""y"": 0, ""z"": 0}, ""location"": {""method"": ""descriptor"", ""value"": ""back_left_corner""}}]}","True","False","0.6842105263157895","0.6842105263157895","0.6842105263157895","0.6842105263157895","0.6842105263157895","0.6842105263157895","0.9313725490196079","7.0","8.596482276916504"
