"num_shots","prompt","expected_json_str","generated_json_str","valid_json","schema_match","key_f1","key_precision","key_recall","item_f1","item_precision","item_recall","tree_edit_similarity","tree_edit_distance","generation_time"
"50","Build a box from concrete with dimensions 15 by 25 by 70mm. Place roller at the bottom center point ","{""geometry"": {""type"": ""box"", ""dimensions"": {""length"": 15, ""width"": 25, ""height"": 70}, ""origin"": {""x"": 0, ""y"": 0, ""z"": 0}, ""orientation"": {""primary_axis"": ""z""}}, ""material"": {""type"": ""CONCRETE""}, ""boundary_conditions"": [{""type"": ""roller"", ""location"": {""method"": ""descriptor"", ""value"": ""bottom_center_point""}}], ""loads"": [{""type"": ""pressure"", ""magnitude"": 1500000, ""location"": {""method"": ""descriptor"", ""value"": ""back_face""}}]}","INVALID","False","False","0.0","0.0","0.0","0.0","0.0","0.0","0.0","inf","67.61482167243958"
"50","Model a box made of pla. Dimensions: 65 by 60 by 48mm. Roller constraint at the top face. 7.0MPa pre","{""geometry"": {""type"": ""box"", ""dimensions"": {""length"": 65, ""width"": 60, ""height"": 48}, ""origin"": {""x"": 0, ""y"": 0, ""z"": 0}, ""orientation"": {""primary_axis"": ""z""}}, ""material"": {""type"": ""PLA""}, ""boundary_conditions"": [{""type"": ""roller"", ""location"": {""method"": ""descriptor"", ""value"": ""top_face""}}], ""loads"": [{""type"": ""pressure"", ""magnitude"": 7000000, ""location"": {""method"": ""descriptor"", ""value"": ""back_face""}}]}","INVALID","False","False","0.0","0.0","0.0","0.0","0.0","0.0","0.0","inf","67.03178715705872"
"50","Make a concrete sphere part with 20mm radius. Apply roller constraint at the center point and pressu","{""geometry"": {""type"": ""sphere"", ""dimensions"": {""outer_radius"": 20, ""inner_radius"": 0}, ""origin"": {""x"": 0, ""y"": 0, ""z"": 0}, ""orientation"": {""primary_axis"": ""z""}}, ""material"": {""type"": ""CONCRETE""}, ""boundary_conditions"": [{""type"": ""roller"", ""location"": {""method"": ""descriptor"", ""value"": ""center_point""}}], ""loads"": [{""type"": ""pressure"", ""magnitude"": 5000000, ""location"": {""method"": ""descriptor"", ""value"": ""outer_surface""}}]}","INVALID","False","False","0.0","0.0","0.0","0.0","0.0","0.0","0.0","inf","64.02414965629578"
"50","FEA setup: sphere geometry, pla material, size radius 35mm. Support with pin the bottom left corner,","{""geometry"": {""type"": ""sphere"", ""dimensions"": {""outer_radius"": 35, ""inner_radius"": 0}, ""origin"": {""x"": 0, ""y"": 0, ""z"": 0}, ""orientation"": {""primary_axis"": ""z""}}, ""material"": {""type"": ""PLA""}, ""boundary_conditions"": [{""type"": ""pinned"", ""location"": {""method"": ""descriptor"", ""value"": ""bottom_left_corner""}}], ""loads"": [{""type"": ""force"", ""magnitude"": 90, ""direction"": [0, 0, 1], ""location"": {""method"": ""descriptor"", ""value"": ""top_left_corner""}}]}","INVALID","False","False","0.0","0.0","0.0","0.0","0.0","0.0","0.0","inf","67.16156268119812"
"50","Model a cylinder made of titanium gr2. Dimensions: 38mm radius and 145mm height. Pin the left face. ","{""geometry"": {""type"": ""cylinder"", ""dimensions"": {""outer_radius"": 38, ""height"": 145, ""inner_radius"": 0}, ""origin"": {""x"": 0, ""y"": 0, ""z"": 0}, ""orientation"": {""primary_axis"": ""z""}}, ""material"": {""type"": ""TITANIUM_GR2""}, ""boundary_conditions"": [{""type"": ""pinned"", ""location"": {""method"": ""descriptor"", ""value"": ""left_face""}}], ""loads"": [{""type"": ""force"", ""magnitude"": 40, ""direction"": [0, 1, 0], ""location"": {""method"": ""descriptor"", ""value"": ""top_center_point""}}]}","INVALID","False","False","0.0","0.0","0.0","0.0","0.0","0.0","0.0","inf","60.96544098854065"
